- hosts: all
  roles:
     - role: dj-wasabi.zabbix-agent
       agent_server: 192.168.10.178
       agent_serveractive: 192.168.10.178
       zabbix_url: http://192.168.10.178/zabbix
       zabbix_api_use: true
       zabbix_api_user: Admin
       zabbix_api_pass: zabbix
       zabbix_create_host: present
       zabbix_host_groups:
         - Linux Servers
       zabbix_link_templates:
         - Template OS Linux
         - Apache APP Template
       #zabbix_macros:
       #  - macro_key: apache_type
       #    macro_value: reverse_proxy
