- hosts: all
  roles:
     - role: avanov.pyenv
       pyenv_path: "{{ home }}/pyenv"
       pyenv_owner: "{{ instance_owner }}"
       pyenv_update_git_install: no
       pyenv_python_versions:
         - "{{ python_version }}"
         #- "2.7.8"
       pyenv_virtualenvs:
         - venv_name: "latest_v3"
           py_version: "3.4.1"

         - venv_name: "latest_v2"
           py_version: "2.7.8"
