---
- name: download spark...
  become: yes
  become_user: root
  get_url: >
    url={{spark_url}}
    dest=/tmp/{{spark_tgz}}
    owner=root
    group=root
    mode=0644

- name: install spark to /opt...
  become: yes
  become_user: root
  unarchive: >
    copy=no
    dest=/opt
    src=/tmp/{{spark_tgz}}
    creates={{spark_target_dir}}

- name: link /opt/spark...
  become: yes
  become_user: root
  file: >
    src={{spark_target_dir}}
    dest=/opt/spark
    state=link
    owner=root
    group=root

- name: include spark in the default path...
  become: yes
  become_user: root
  copy: >
    src=etc/profile.d/spark.sh
    dest=/etc/profile.d/spark.sh
    owner=root
    group=root
    mode=0644
